import type { ApplicationHandlers } from '../ipc/application-handlers';

export const webMethods = {
  'connections:command': 'connectionCommand',
  'nodes:command': 'nodePackageCommand',
  'providers:command': 'providerCommand',
  'app:get-version': 'getVersion',
  'app:show-main-window': 'showMainWindow',
  'app:quit-application': 'quitApplication',
  'config:get-bootstrap-state': 'getBootstrapState',
  'config:patch-settings': 'patchLocalSettings',
  'config:test-llm': 'testLlmConnection',
  'bots:list': 'listBots',
  'bots:create-draft': 'createDraftBot',
  'workbench:get': 'getWorkbench',
  'workbench:stop-agent': 'stopWorkbenchAgent',
  'workbench:send-message': 'sendWorkbenchMessage',
  'workbench:run-backtest': 'runWorkbenchBacktest',
  'workbench:configure-node': 'configureLegacyNode',
  'workbench:approve-revision': 'approveStrategyRevision',
  'workbench:get-trace': 'getWorkbenchTrace',
  'deployments:start-paper': 'startPaperDeployment',
  'deployments:get-paper': 'getPaperDeployment',
  'deployments:pause-paper': 'pausePaperDeployment',
  'deployments:stop-paper': 'stopPaperDeployment',
  'deployments:prepare-live': 'prepareLiveDeployment',
  'deployments:start-live': 'startLiveDeployment',
  'deployments:get-live': 'getLiveDeployment',
  'deployments:stop-live': 'stopLiveDeployment',
  'deployments:get-active': 'getActiveDeployment',
  'runtime:get-status': 'getRuntimeStatus',
  'runtime:get-database-state': 'getDatabaseState',
} as const satisfies Record<string, keyof ApplicationHandlers>;
