import { useEffect, useRef, useState } from 'react';
import { Badge, Banner, Button, Collapsible, Input, LayerCard, Select, Switch, Table } from '@cloudflare/kumo';
import { PlayIcon, StopIcon } from '@phosphor-icons/react';
import { FlowBacktestSettingsSchema, type CatbotsDesktopApi, type ChatFlowDraft, type FlowBacktestJob, type FlowBacktestSettings } from '@catbots/contracts';
import { EquityCurve } from './EquityCurve';
const money=(value:number)=>value.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const stamp=(value:string)=>value.slice(0,16);
function defaults():FlowBacktestSettings { const to=Math.floor(Date.now()/3600000)*3600000;return {market:'ETH-PERP',from:new Date(to-7*86400000).toISOString(),to:new Date(to).toISOString(),timeframe:'1h',startingCapital:10000,feeBps:3.5,slippageBps:1}; }
export function FlowBacktestPanel({draft,api,disabled=false}:{draft:ChatFlowDraft;api?:CatbotsDesktopApi['nodes'];disabled?:boolean}) {
  const [settings,setSettings]=useState(defaults),[refresh,setRefresh]=useState(false),[job,setJob]=useState<FlowBacktestJob|null>(null),[error,setError]=useState(''),[starting,setStarting]=useState(false),[page,setPage]=useState(0);
  const storageKey=`catbots.backtest-job:${draft.botId}`;
  const [jobId,setJobId]=useState(()=>{try{return sessionStorage.getItem(storageKey)??'';}catch{return '';}});
  const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
  useEffect(()=>{if(!api||!jobId)return;let active=true;let timer:ReturnType<typeof setTimeout>;
    const poll=async()=>{try{const response=await api.command({action:'backtest_status',botId:draft.botId,jobId});if(!active)return;if(!response.backtest)throw new Error();setJob(response.backtest);if(['loading','running'].includes(response.backtest.status))timer=setTimeout(()=>void poll(),750);}catch{if(active)setError('Run is no longer available. The backend may have restarted; run again to restore cached results.');}};
    void poll();return()=>{active=false;clearTimeout(timer);};
  },[api,jobId,draft.botId]);
  const busy=starting||job?.status==='loading'||job?.status==='running';
  const result=job?.result;
  const start=async()=>{const parsed=FlowBacktestSettingsSchema.safeParse(settings);if(!parsed.success){setError(parsed.error.issues.map(issue=>issue.message).join('; '));return;}if(!api)return;setStarting(true);setError('');setPage(0);
    try{const response=await api.command({action:'backtest_flow',botId:draft.botId,version:draft.version,settings:parsed.data,refresh});if(!alive.current)return;if(!response.backtest)throw new Error();setJob(response.backtest);setJobId(response.backtest.id);try{sessionStorage.setItem(storageKey,response.backtest.id);}catch{}}
    catch{if(alive.current)setError('Could not start. Save node changes, reload the flow, or wait for another active backtest to finish.');}finally{if(alive.current)setStarting(false);}};
  const chart=result?result.equityCurve.filter((_,index,all)=>index===0||index===all.length-1||index%Math.max(1,Math.ceil(all.length/400))===0).map(point=>({timestamp:new Date(point.at).toISOString(),equity:String(point.equity)})):[];
  return <section className="backtest-panel" aria-label="Historical flow backtest">
    <header className="backtest-toolbar"><div><p className="eyebrow">HISTORICAL MARKET REPLAY</p><h2>Backtest flow v{draft.version}</h2></div><Button size="base" variant="primary" icon={PlayIcon} disabled={busy||disabled||!api} loading={starting} onClick={()=>void start()}>Run historical backtest</Button>{busy&&job&&<Button size="base" variant="secondary" icon={StopIcon} onClick={async()=>{try{const response=await api?.command({action:'cancel_backtest',botId:draft.botId,jobId:job.id});if(response?.backtest)setJob(response.backtest);}catch{setError('Could not cancel; retry or wait for completion.');}}}>Cancel backtest</Button>}</header>
    <p>Hyperliquid historical candles and hourly funding · UTC · signals at close, fills from the next bar.</p>
    <div className="backtest-assumption-form"><Input size="base" label="Market" value={settings.market} disabled={busy} onChange={event=>setSettings({...settings,market:event.target.value})}/>
      <Input size="base" label="From (UTC)" type="datetime-local" value={stamp(settings.from)} disabled={busy} onChange={event=>setSettings({...settings,from:event.target.value?`${event.target.value}:00.000Z`:''})}/>
      <Input size="base" label="To (UTC, exclusive)" type="datetime-local" value={stamp(settings.to)} disabled={busy} onChange={event=>setSettings({...settings,to:event.target.value?`${event.target.value}:00.000Z`:''})}/>
      <Select size="base" label="Replay interval" value={settings.timeframe} disabled={busy} onValueChange={value=>setSettings({...settings,timeframe:value as FlowBacktestSettings['timeframe']})}>{['1m','5m','15m','1h'].map(value=><Select.Option key={value} value={value}>{value}</Select.Option>)}</Select>
      {(['startingCapital','feeBps','slippageBps'] as const).map((key,index)=><Input key={key} size="base" type="number" label={['Starting capital (USD)','Fee per fill (bps)','Market slippage (bps)'][index]} value={settings[key]} min={0} disabled={busy} onChange={event=>setSettings({...settings,[key]:Number(event.target.value)})}/>)}</div>
    <Switch label="Refresh historical data and recompute (bypass cache)" checked={refresh} onCheckedChange={setRefresh}/>
    {disabled&&<p>Save or reset unsaved node configurations and wait for AI to finish before running.</p>}
    {error&&<Banner variant="error" title="Backtest needs attention" description={error}/>}
    {job&&<p role="status"><Badge variant={job.status==='completed'?'success':'info'}>{job.status}</Badge> {job.status==='loading'?'Loading and validating market history':`${Math.round(job.progress*100)}%`} · {job.cacheHit?'Cached result':'New run'}</p>}
    {job?.error&&<Banner variant="error" title="Backtest failed" description={job.error}/>}
    {result?<><div className="backtest-provenance"><Badge variant="info">Flow v{job.version}</Badge><span>{result.settings.market} · {result.settings.from} → {result.settings.to}</span></div>{job.version!==draft.version&&<Banner variant="alert" title="Older flow result" description="This result belongs to a previous saved flow version. Run again to test the current flow."/>}
      <div className="metric-grid">{[['Final equity',money(result.finalEquity)],['Return',`${result.returnPercent.toFixed(2)}%`],['Drawdown (bar close)',`${result.maxDrawdownPercent.toFixed(2)}%`],['Fills',String(result.fills.length)],['Fees / funding',`${money(result.fees)} / ${money(result.funding)}`],['Realized / unrealized PnL',`${money(result.realizedPnl)} / ${money(result.unrealizedPnl)}`]].map(([label,value])=><LayerCard className="metric-card" key={label}><span>{label}</span><strong>{value}</strong></LayerCard>)}</div>
      <p>{result.dataset.bars} replay bars · {result.durationMs.toFixed(0)} ms {job.cacheHit?'original compute':'compute'} · {result.rejectedOrders} rejected orders · {result.pendingOrders} pending at end · Position {result.position.quantity} @ {money(result.position.entryPrice)}</p>
      <EquityCurve points={chart}/><p>Chart sampled for display; metrics use every replay bar.</p>
      <LayerCard className="backtest-trades"><h3>Fills</h3><p>Market fills are at the next open. Intrabar limit fills use the bar’s opening timestamp as a bucket, not an exact execution time.</p><Table aria-label="Historical fills"><Table.Header><Table.Row>{['Time (UTC)','Side','Quantity','Price','Fee','Realized PnL'].map(label=><Table.Head key={label}>{label}</Table.Head>)}</Table.Row></Table.Header><Table.Body>{result.fills.slice(page*50,page*50+50).map((fill,index)=><Table.Row key={index}><Table.Cell>{new Date(fill.at).toISOString()}</Table.Cell><Table.Cell>{fill.side}</Table.Cell><Table.Cell>{fill.quantity}</Table.Cell><Table.Cell>{money(fill.price)}</Table.Cell><Table.Cell>{money(fill.fee)}</Table.Cell><Table.Cell>{money(fill.realizedPnl)}</Table.Cell></Table.Row>)}</Table.Body></Table>{!result.fills.length&&<p>No fills in this period. Review node coverage and strategy conditions.</p>}<div className="provider-actions"><Button size="sm" variant="secondary" disabled={!page} onClick={()=>setPage(page-1)}>Previous fills</Button><span>{page+1} / {Math.max(1,Math.ceil(result.fills.length/50))}</span><Button size="sm" variant="secondary" disabled={(page+1)*50>=result.fills.length} onClick={()=>setPage(page+1)}>Next fills</Button></div></LayerCard>
      <Collapsible.Root><Collapsible.Trigger render={<Button size="sm" variant="secondary"/>}>Node coverage and reproducibility</Collapsible.Trigger><Collapsible.Panel className="backtest-node-coverage"><Table aria-label="Backtest node coverage"><Table.Header><Table.Row><Table.Head>Node</Table.Head><Table.Head>Executed</Table.Head><Table.Head>Skipped</Table.Head><Table.Head>Unavailable</Table.Head></Table.Row></Table.Header><Table.Body>{Object.entries(result.nodeStats).map(([id,stats])=><Table.Row key={id}><Table.Cell>{id}</Table.Cell><Table.Cell>{stats.executed}</Table.Cell><Table.Cell>{stats.skipped}</Table.Cell><Table.Cell>{stats.unavailable}</Table.Cell></Table.Row>)}</Table.Body></Table><p>Engine: {result.engineVersion}</p><p className="package-integrity">Flow: {result.flowHash}<br/>Data: {result.dataHash}</p><p>Data fetched: {result.dataset.fetchedAt}</p><pre>{JSON.stringify(result.settings,null,2)}</pre></Collapsible.Panel></Collapsible.Root>
      {result.warnings.map(warning=><Banner key={warning} variant="alert" title="Replay assumption" description={warning}/>)}</>:!busy&&<LayerCard className="backtest-empty"><h3>Test your saved flow on historical data</h3><p>Up to 5,000 recent candles per interval, including indicator warm-up. Missing history stops the run; results are never substituted with sample data.</p></LayerCard>}
  </section>;
}
