import { useEffect, useState } from 'react';
import { Badge, Banner, Button, Input, LayerCard, Switch, Textarea } from '@cloudflare/kumo';
import { exampleNodePackage, type CatbotsDesktopApi, type NodePackageCommand, type NodePackageStatus, type CommunityNode } from '@catbots/contracts';
export function NodesScreen({ api }: { api: NonNullable<CatbotsDesktopApi['nodes']> }) {
  const [state, setState] = useState<NodePackageStatus>({ packages: [] });
  const [source, setSource] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { let active = true; void api.command({ action: 'list' }).then((value) => { if (active) setState(value); }).catch(() => { if (active) setError('Could not load node packages.'); }); return () => { active = false; }; }, [api]);
  const run = async (input: NodePackageCommand) => { setBusy(true); setError(''); try { setState(await api.command(input)); if (input.action === 'install') setSource(''); } catch { setError('Package rejected. Check the manifest, publisher namespace, version, built-in nodes and port mappings. Existing packages have been kept.'); } finally { setBusy(false); } };
  return <div className="settings-shell"><section className="setup-intro"><h1>Nodes</h1><p>Install reusable community subflows. Installed nodes become available to the strategy assistant.</p></section>
    {error && <Banner variant="error" title="Node packages" description={error} />}
    <LayerCard className="settings-card provider-connections"><h2>Discover</h2><p>Starter package · Catbots Funding Filter</p><p>Builds on the built-in funding predicate. Runs on the same market snapshots as your other nodes.</p><div className="provider-actions"><Button disabled={busy} onClick={() => void run({ action: 'install', source: JSON.stringify(exampleNodePackage) })}>Install Funding Filter</Button><Button variant="secondary" onClick={() => setSource(JSON.stringify(exampleNodePackage, null, 2))}>Inspect manifest</Button></div><p>Community publishing starts with portable JSON packages. Public registry discovery is not connected yet.</p></LayerCard>
    <LayerCard className="settings-card provider-connections"><h2>Install a package</h2><Textarea label="Package manifest JSON" value={source} onChange={(event) => setSource(event.target.value)} rows={5} /><Button disabled={busy || !source.trim()} onClick={() => void run({ action: 'install', source })}>Validate and install</Button><p>Declarative subflows only. No JavaScript, installation scripts or custom UI is executed.</p></LayerCard>
    <h2>Installed & archived</h2>{!state.packages.length && <p>No packages installed yet.</p>}
    {state.packages.map((item) => <LayerCard key={item.integrity} className="settings-card provider-connections"><header><h3>{item.manifest.name}</h3><Badge variant="secondary">{item.manifest.version} · {item.enabled ? 'Enabled' : 'Archived'}</Badge></header><p>License: {item.manifest.license}</p><p className="package-integrity">{item.integrity}</p><Button variant="secondary" disabled={busy} onClick={() => void run({ action: 'enable', integrity: item.integrity, enabled: !item.enabled })}>{item.enabled ? 'Disable for new drafts' : 'Enable this version'}</Button><p>Saved revisions keep their expanded graph. Enabling another version affects new drafts only.</p>{item.manifest.nodes.map((node) => <NodeFields key={node.type} node={node} />)}</LayerCard>)}
  </div>;
}
function NodeFields({ node }: { node: CommunityNode }) {
  const [values, setValues] = useState<Record<string, string | number | boolean>>(() => Object.fromEntries(Object.entries(node.fields).map(([key, field]) => [key, field.default])));
  const [copied, setCopied] = useState(false);
  return <section className="provider-login"><h3>{node.title}</h3><p>{node.description}</p><p>{node.kind} · {node.type} · definition v{node.version}</p>
    {Object.entries(node.fields).map(([key, field]) => field.type === 'boolean' ? <Switch key={key} label={field.label} checked={!!values[key]} onCheckedChange={(value) => setValues((current) => ({ ...current, [key]: value }))} /> : <Input key={key} label={field.label} type={field.type === 'number' ? 'number' : 'text'} value={String(values[key] ?? '')} min={field.type === 'number' ? field.minimum : undefined} max={field.type === 'number' ? field.maximum : undefined} onChange={(event) => setValues((current) => ({ ...current, [key]: event.target.value }))} />)}
    <Button variant="secondary" onClick={() => { const config = Object.fromEntries(Object.entries(node.fields).map(([key, field]) => [key, field.type === 'number' ? Number(values[key]) : values[key]])); void navigator.clipboard.writeText(`Use ${node.type} version ${node.version} with config ${JSON.stringify(config)} in my strategy. Ask about any missing entry, exit or risk rules.`).then(() => setCopied(true)).catch(() => setCopied(false)); }}>{copied ? 'Copied' : 'Copy instruction for chat'}</Button>
  </section>;
}
